### ISSUE TITLE
Externalize github-team-data.xml

### ISSUE THREAD

**Issue by wolfc** [jboss-set/mjolnir#20]
github-team-data.xml must not be part of the war.

**Comment by TomasHofman** [comment]
I was looking at options how this could be done an found two:

1) Deployment overlay - feels bit cumbersome, since the application must be deployed first (with the wrong configuration) and then linked with overlay and redeployed. Plus it's not very intuitive.

2) Define system property that would point to configuration file/directory for the application, so the application configuration would reside at some permanent place on the filesystem.

I would go for 2).

**Comment by TomasHofman** [comment]
Configuration went to database. This should be closed.

**Comment by TomasHofman** [comment]
Closing as this configuration was moved to database.
